import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  Button,
  Flex,
  Heading,
  Menu,
  MenuButton,
  MenuItem,
  MenuList,
  Spinner,
} from "@chakra-ui/react";
import { Providers } from "./providers";
import { Wrapper } from "@/components/lib/Wrapper";
import Link from "next/link";
import { Suspense } from "react";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {session ? (
          <Suspense fallback={<Spinner />}>
            <Providers>
              <Wrapper>
                <Flex justifyContent="space-between">
                  <Link href="/">
                    <Heading
                      cursor="pointer"
                      mb="5"
                      size="lg"
                      border="1px solid black"
                      p="5"
                      borderRadius="5"
                    >
                      Treningsutfordring
                    </Heading>
                  </Link>
                  <Flex justifyContent="flex-end">
                    <Menu>
                      <MenuButton as={Button}>Meny</MenuButton>
                      <MenuList>
                        <Link href="/settings" passHref>
                          <MenuItem>Innstillinger</MenuItem>
                        </Link>
                      </MenuList>
                    </Menu>
                  </Flex>
                </Flex>
                {children}
              </Wrapper>
            </Providers>
          </Suspense>
        ) : (
          <Wrapper>
            <h1>Utlogget</h1>
            <p>
              Du må logge inn.{" "}
              <Button>
                <Link href={"/api/auth/signin"}>Gå her</Link>
              </Button>
            </p>
          </Wrapper>
        )}
      </body>
    </html>
  );
}
